### ISSUE TITLE
Markbot is being stupid @charlie-quinn

### ISSUE THREAD

**Issue by briannabeauchamp** [briannabeauchamp/only-keyboards-allowed#1]
Hi Charlie, my 320px screenshot isn't working properly so it won't let me submit my assignment. Help! @charlie-quinn

**Comment by charlie-quinn** [comment]
Grade has been updated manually. 🤖 ✅

**Comment by charlie-quinn** [comment]
⚠️`Reminder: please close this issue once it has been resolved.`
